<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'category_id' => 1,
                'name' => 'Salted Creme Brulee',
                'slug' => 'Salted Creme Brulee',
                'description' => 'Nikmati kesegaran Salted Creme Brulee khas Sebatas Kopi.',
                'price' => '28000.00',
                'stock' => 100,
                'image' => 'products/Salted Creme Brulee.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            1 => 
            array (
                'id' => 2,
                'category_id' => 1,
                'name' => 'No Name',
                'slug' => 'No Name',
                'description' => 'Nikmati kesegaran No Name khas Sebatas Kopi.',
                'price' => '28000.00',
                'stock' => 100,
                'image' => 'products/No Name.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            2 => 
            array (
                'id' => 3,
                'category_id' => 1,
                'name' => 'Terserah Kopi Susu',
                'slug' => 'Terserah Kopi Susu',
                'description' => 'Nikmati kesegaran Terserah Kopi Susu khas Sebatas Kopi.',
                'price' => '27000.00',
                'stock' => 100,
                'image' => 'products/Terserah Kopi Susu.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            3 => 
            array (
                'id' => 4,
                'category_id' => 1,
                'name' => 'Sekedar Kopi Susu',
                'slug' => 'Sekedar Kopi Susu',
                'description' => 'Nikmati kesegaran Sekedar Kopi Susu khas Sebatas Kopi.',
                'price' => '25000.00',
                'stock' => 100,
                'image' => 'products/Sekedar Kopi Susu.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            4 => 
            array (
                'id' => 5,
                'category_id' => 1,
                'name' => 'Kopi Susu Biasa Aja',
                'slug' => 'Kopi Susu Biasa Aja',
                'description' => 'Nikmati kesegaran Kopi Susu Biasa Aja khas Sebatas Kopi.',
                'price' => '25000.00',
                'stock' => 100,
                'image' => 'products/Kopi Susu Biasa Aja.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            5 => 
            array (
                'id' => 6,
                'category_id' => 1,
                'name' => 'Irish Coffee',
                'slug' => 'Irish Coffee',
                'description' => 'Nikmati kesegaran Irish Coffee khas Sebatas Kopi.',
                'price' => '25000.00',
                'stock' => 100,
                'image' => 'products/Irish Coffee.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            6 => 
            array (
                'id' => 7,
                'category_id' => 1,
                'name' => 'Ngaspal',
                'slug' => 'Ngaspal',
                'description' => 'Nikmati kesegaran Ngaspal khas Sebatas Kopi.',
                'price' => '25000.00',
                'stock' => 100,
                'image' => 'products/Ngaspal.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            7 => 
            array (
                'id' => 8,
                'category_id' => 1,
                'name' => 'Matcha Caramel',
                'slug' => 'Matcha Caramel',
                'description' => 'Nikmati kesegaran Matcha Caramel khas Sebatas Kopi.',
                'price' => '20000.00',
                'stock' => 100,
                'image' => 'products/Matcha Caramel.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            8 => 
            array (
                'id' => 9,
                'category_id' => 1,
                'name' => 'Vanilla Caramel',
                'slug' => 'Vanilla Caramel',
                'description' => 'Nikmati kesegaran Vanilla Caramel khas Sebatas Kopi.',
                'price' => '20000.00',
                'stock' => 100,
                'image' => 'products/Vanilla Caramel.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            9 => 
            array (
                'id' => 10,
                'category_id' => 1,
                'name' => 'Taro Caramel',
                'slug' => 'Taro Caramel',
                'description' => 'Nikmati kesegaran Taro Caramel khas Sebatas Kopi.',
                'price' => '20000.00',
                'stock' => 100,
                'image' => 'products/Taro Caramel.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            10 => 
            array (
                'id' => 11,
                'category_id' => 2,
                'name' => 'Americano Hot',
                'slug' => 'Americano Hot',
                'description' => 'Nikmati kesegaran Americano Hot khas Sebatas Kopi.',
                'price' => '15000.00',
                'stock' => 100,
                'image' => 'products/Americano.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            11 => 
            array (
                'id' => 12,
                'category_id' => 2,
                'name' => 'Americano Cold',
                'slug' => 'Americano Cold',
                'description' => 'Nikmati kesegaran Americano Cold khas Sebatas Kopi.',
                'price' => '18000.00',
                'stock' => 100,
                'image' => 'products/Americano.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            12 => 
            array (
                'id' => 13,
                'category_id' => 2,
                'name' => 'Sanger Hot',
                'slug' => 'Sanger Hot',
                'description' => 'Nikmati kesegaran Sanger Hot khas Sebatas Kopi.',
                'price' => '15000.00',
                'stock' => 100,
                'image' => 'products/Sanger.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            13 => 
            array (
                'id' => 14,
                'category_id' => 2,
                'name' => 'Sanger Cold',
                'slug' => 'Sanger Cold',
                'description' => 'Nikmati kesegaran Sanger Cold khas Sebatas Kopi.',
                'price' => '18000.00',
                'stock' => 100,
                'image' => 'products/Sanger.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            14 => 
            array (
                'id' => 15,
                'category_id' => 2,
                'name' => 'Coffee Chocolate Hot',
                'slug' => 'Coffee Chocolate Hot',
                'description' => 'Nikmati kesegaran Coffee Chocolate Hot khas Sebatas Kopi.',
                'price' => '15000.00',
                'stock' => 100,
                'image' => 'products/Coffee Chocolate.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            15 => 
            array (
                'id' => 16,
                'category_id' => 2,
                'name' => 'Coffee Chocolate Cold',
                'slug' => 'Coffee Chocolate Cold',
                'description' => 'Nikmati kesegaran Coffee Chocolate Cold khas Sebatas Kopi.',
                'price' => '18000.00',
                'stock' => 100,
                'image' => 'products/Coffee Chocolate.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            16 => 
            array (
                'id' => 17,
                'category_id' => 2,
                'name' => 'Coffee Milo Hot',
                'slug' => 'Coffee Milo Hot',
                'description' => 'Nikmati kesegaran Coffee Milo Hot khas Sebatas Kopi.',
                'price' => '20000.00',
                'stock' => 100,
                'image' => 'products/Coffee Milo.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            17 => 
            array (
                'id' => 18,
                'category_id' => 2,
                'name' => 'Coffee Milo Cold',
                'slug' => 'Coffee Milo Cold',
                'description' => 'Nikmati kesegaran Coffee Milo Cold khas Sebatas Kopi.',
                'price' => '23000.00',
                'stock' => 100,
                'image' => 'products/Coffee Milo.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            18 => 
            array (
                'id' => 19,
                'category_id' => 2,
                'name' => 'Caramel Macchiato Hot',
                'slug' => 'Caramel Macchiato Hot',
                'description' => 'Nikmati kesegaran Caramel Macchiato Hot khas Sebatas Kopi.',
                'price' => '23000.00',
                'stock' => 100,
                'image' => 'products/Caramel Macchiato.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            19 => 
            array (
                'id' => 20,
                'category_id' => 2,
                'name' => 'Caramel Macchiato Cold',
                'slug' => 'Caramel Macchiato Cold',
                'description' => 'Nikmati kesegaran Caramel Macchiato Cold khas Sebatas Kopi.',
                'price' => '25000.00',
                'stock' => 100,
                'image' => 'products/Caramel Macchiato.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            20 => 
            array (
                'id' => 21,
                'category_id' => 2,
                'name' => 'Sebatas Kopi Susu Hot',
                'slug' => 'Sebatas Kopi Susu Hot',
                'description' => 'Nikmati kesegaran Sebatas Kopi Susu Hot khas Sebatas Kopi.',
                'price' => '22000.00',
                'stock' => 100,
                'image' => 'products/Sebatas Kopi Susu.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            21 => 
            array (
                'id' => 22,
                'category_id' => 2,
                'name' => 'Sebatas Kopi Susu Cold',
                'slug' => 'Sebatas Kopi Susu Cold',
                'description' => 'Nikmati kesegaran Sebatas Kopi Susu Cold khas Sebatas Kopi.',
                'price' => '25000.00',
                'stock' => 100,
                'image' => 'products/Sebatas Kopi Susu.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            22 => 
            array (
                'id' => 23,
                'category_id' => 2,
                'name' => 'White Chocolate Coffee Hot',
                'slug' => 'White Chocolate Coffee Hot',
                'description' => 'Nikmati kesegaran White Chocolate Coffee Hot khas Sebatas Kopi.',
                'price' => '23000.00',
                'stock' => 100,
                'image' => 'products/White Chocolate Coffee.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            23 => 
            array (
                'id' => 24,
                'category_id' => 2,
                'name' => 'White Chocolate Coffee Cold',
                'slug' => 'White Chocolate Coffee Cold',
                'description' => 'Nikmati kesegaran White Chocolate Coffee Cold khas Sebatas Kopi.',
                'price' => '25000.00',
                'stock' => 100,
                'image' => 'products/White Chocolate Coffee.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            24 => 
            array (
                'id' => 25,
                'category_id' => 3,
                'name' => 'Es Kopi Regal',
                'slug' => 'Es Kopi Regal',
                'description' => 'Nikmati kesegaran Es Kopi Regal khas Sebatas Kopi.',
                'price' => '18000.00',
                'stock' => 100,
                'image' => 'products/Es Kopi Regal.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            25 => 
            array (
                'id' => 26,
                'category_id' => 3,
                'name' => 'Es Kopi Strawberry',
                'slug' => 'Es Kopi Strawberry',
                'description' => 'Nikmati kesegaran Es Kopi Strawberry khas Sebatas Kopi.',
                'price' => '22000.00',
                'stock' => 100,
                'image' => 'products/Es Kopi Strawberry.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            26 => 
            array (
                'id' => 27,
                'category_id' => 3,
                'name' => 'Es Kopi Caramel',
                'slug' => 'Es Kopi Caramel',
                'description' => 'Nikmati kesegaran Es Kopi Caramel khas Sebatas Kopi.',
                'price' => '22000.00',
                'stock' => 100,
                'image' => 'products/Es Kopi Caramel.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            27 => 
            array (
                'id' => 28,
                'category_id' => 3,
                'name' => 'Es Kopi Vanilla',
                'slug' => 'Es Kopi Vanilla',
                'description' => 'Nikmati kesegaran Es Kopi Vanilla khas Sebatas Kopi.',
                'price' => '22000.00',
                'stock' => 100,
                'image' => 'products/Es Kopi Vanilla.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            28 => 
            array (
                'id' => 29,
                'category_id' => 3,
                'name' => 'Es Kopi Taro',
                'slug' => 'Es Kopi Taro',
                'description' => 'Nikmati kesegaran Es Kopi Taro khas Sebatas Kopi.',
                'price' => '22000.00',
                'stock' => 100,
                'image' => 'products/Es Kopi Taro.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            29 => 
            array (
                'id' => 30,
                'category_id' => 3,
                'name' => 'Es Kopi Red Velvet',
                'slug' => 'Es Kopi Red Velvet',
                'description' => 'Nikmati kesegaran Es Kopi Red Velvet khas Sebatas Kopi.',
                'price' => '22000.00',
                'stock' => 100,
                'image' => 'products/Es Kopi Red Velvet.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            30 => 
            array (
                'id' => 31,
                'category_id' => 3,
                'name' => 'Es Kopi Matcha',
                'slug' => 'Es Kopi Matcha',
                'description' => 'Nikmati kesegaran Es Kopi Matcha khas Sebatas Kopi.',
                'price' => '22000.00',
                'stock' => 100,
                'image' => 'products/Es Kopi Matcha.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            31 => 
            array (
                'id' => 32,
                'category_id' => 3,
                'name' => 'Es Kopi Kocok',
                'slug' => 'Es Kopi Kocok',
                'description' => 'Nikmati kesegaran Es Kopi Kocok khas Sebatas Kopi.',
                'price' => '18000.00',
                'stock' => 100,
                'image' => 'products/Es Kopi Kocok.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            32 => 
            array (
                'id' => 33,
                'category_id' => 3,
                'name' => 'Es Kopi Gula Aren',
                'slug' => 'Es Kopi Gula Aren',
                'description' => 'Nikmati kesegaran Es Kopi Gula Aren khas Sebatas Kopi.',
                'price' => '22000.00',
                'stock' => 100,
                'image' => 'products/Es Kopi Gula Aren.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            33 => 
            array (
                'id' => 34,
                'category_id' => 4,
                'name' => 'Milo Latte Hot',
                'slug' => 'Milo Latte Hot',
                'description' => 'Nikmati kesegaran Milo Latte Hot khas Sebatas Kopi.',
                'price' => '13000.00',
                'stock' => 100,
                'image' => 'products/Milo Latte.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            34 => 
            array (
                'id' => 35,
                'category_id' => 4,
                'name' => 'Milo Latte Cold',
                'slug' => 'Milo Latte Cold',
                'description' => 'Nikmati kesegaran Milo Latte Cold khas Sebatas Kopi.',
                'price' => '15000.00',
                'stock' => 100,
                'image' => 'products/Milo Latte.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            35 => 
            array (
                'id' => 36,
                'category_id' => 4,
                'name' => 'Strawberry Latte Hot',
                'slug' => 'Strawberry Latte Hot',
                'description' => 'Nikmati kesegaran Strawberry Latte Hot khas Sebatas Kopi.',
                'price' => '13000.00',
                'stock' => 100,
                'image' => 'products/Strawberry Latte.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            36 => 
            array (
                'id' => 37,
                'category_id' => 4,
                'name' => 'Strawberry Latte Cold',
                'slug' => 'Strawberry Latte Cold',
                'description' => 'Nikmati kesegaran Strawberry Latte Cold khas Sebatas Kopi.',
                'price' => '15000.00',
                'stock' => 100,
                'image' => 'products/Strawberry Latte.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            37 => 
            array (
                'id' => 38,
                'category_id' => 4,
                'name' => 'Matcha Latte Hot',
                'slug' => 'Matcha Latte Hot',
                'description' => 'Nikmati kesegaran Matcha Latte Hot khas Sebatas Kopi.',
                'price' => '13000.00',
                'stock' => 100,
                'image' => 'products/Matcha Latte.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            38 => 
            array (
                'id' => 39,
                'category_id' => 4,
                'name' => 'Matcha Latte Cold',
                'slug' => 'Matcha Latte Cold',
                'description' => 'Nikmati kesegaran Matcha Latte Cold khas Sebatas Kopi.',
                'price' => '15000.00',
                'stock' => 100,
                'image' => 'products/Matcha Latte.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            39 => 
            array (
                'id' => 40,
                'category_id' => 4,
                'name' => 'Vanilla Latte Hot',
                'slug' => 'Vanilla Latte Hot',
                'description' => 'Nikmati kesegaran Vanilla Latte Hot khas Sebatas Kopi.',
                'price' => '13000.00',
                'stock' => 100,
                'image' => 'products/Vanilla Latte.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            40 => 
            array (
                'id' => 41,
                'category_id' => 4,
                'name' => 'Vanilla Latte Cold',
                'slug' => 'Vanilla Latte Cold',
                'description' => 'Nikmati kesegaran Vanilla Latte Cold khas Sebatas Kopi.',
                'price' => '15000.00',
                'stock' => 100,
                'image' => 'products/Vanilla Latte.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            41 => 
            array (
                'id' => 42,
                'category_id' => 4,
                'name' => 'Caramel Latte Hot',
                'slug' => 'Caramel Latte Hot',
                'description' => 'Nikmati kesegaran Caramel Latte Hot khas Sebatas Kopi.',
                'price' => '13000.00',
                'stock' => 100,
                'image' => 'products/Caramel Latte.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            42 => 
            array (
                'id' => 43,
                'category_id' => 4,
                'name' => 'Caramel Latte Cold',
                'slug' => 'Caramel Latte Cold',
                'description' => 'Nikmati kesegaran Caramel Latte Cold khas Sebatas Kopi.',
                'price' => '15000.00',
                'stock' => 100,
                'image' => 'products/Caramel Latte.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            43 => 
            array (
                'id' => 44,
                'category_id' => 4,
                'name' => 'Taro Latte Hot',
                'slug' => 'Taro Latte Hot',
                'description' => 'Nikmati kesegaran Taro Latte Hot khas Sebatas Kopi.',
                'price' => '13000.00',
                'stock' => 100,
                'image' => 'products/Taro Latte.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            44 => 
            array (
                'id' => 45,
                'category_id' => 4,
                'name' => 'Taro Latte Cold',
                'slug' => 'Taro Latte Cold',
                'description' => 'Nikmati kesegaran Taro Latte Cold khas Sebatas Kopi.',
                'price' => '15000.00',
                'stock' => 100,
                'image' => 'products/Taro Latte.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:45',
                'updated_at' => '2026-08-15 15:16:45',
            ),
            45 => 
            array (
                'id' => 46,
                'category_id' => 4,
                'name' => 'Irish Latte Hot',
                'slug' => 'Irish Latte Hot',
                'description' => 'Nikmati kesegaran Irish Latte Hot khas Sebatas Kopi.',
                'price' => '17000.00',
                'stock' => 100,
                'image' => 'products/Irish Latte.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            46 => 
            array (
                'id' => 47,
                'category_id' => 4,
                'name' => 'Irish Latte Cold',
                'slug' => 'Irish Latte Cold',
                'description' => 'Nikmati kesegaran Irish Latte Cold khas Sebatas Kopi.',
                'price' => '20000.00',
                'stock' => 100,
                'image' => 'products/Irish Latte.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            47 => 
            array (
                'id' => 48,
                'category_id' => 5,
                'name' => 'Teh Vanilla Hot',
                'slug' => 'Teh Vanilla Hot',
                'description' => 'Nikmati kesegaran Teh Vanilla Hot khas Sebatas Kopi.',
                'price' => '13000.00',
                'stock' => 100,
                'image' => 'products/Teh Vanilla.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            48 => 
            array (
                'id' => 49,
                'category_id' => 5,
                'name' => 'Teh Vanilla Cold',
                'slug' => 'Teh Vanilla Cold',
                'description' => 'Nikmati kesegaran Teh Vanilla Cold khas Sebatas Kopi.',
                'price' => '15000.00',
                'stock' => 100,
                'image' => 'products/Teh Vanilla.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            49 => 
            array (
                'id' => 50,
                'category_id' => 5,
                'name' => 'Teh Lemon Hot',
                'slug' => 'Teh Lemon Hot',
                'description' => 'Nikmati kesegaran Teh Lemon Hot khas Sebatas Kopi.',
                'price' => '13000.00',
                'stock' => 100,
                'image' => 'products/Teh Lemon.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            50 => 
            array (
                'id' => 51,
                'category_id' => 5,
                'name' => 'Teh Lemon Cold',
                'slug' => 'Teh Lemon Cold',
                'description' => 'Nikmati kesegaran Teh Lemon Cold khas Sebatas Kopi.',
                'price' => '15000.00',
                'stock' => 100,
                'image' => 'products/Teh Lemon.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            51 => 
            array (
                'id' => 52,
                'category_id' => 5,
                'name' => 'Teh Matcha Hot',
                'slug' => 'Teh Matcha Hot',
                'description' => 'Nikmati kesegaran Teh Matcha Hot khas Sebatas Kopi.',
                'price' => '13000.00',
                'stock' => 100,
                'image' => 'products/Teh Matcha.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            52 => 
            array (
                'id' => 53,
                'category_id' => 5,
                'name' => 'Teh Matcha Cold',
                'slug' => 'Teh Matcha Cold',
                'description' => 'Nikmati kesegaran Teh Matcha Cold khas Sebatas Kopi.',
                'price' => '15000.00',
                'stock' => 100,
                'image' => 'products/Teh Matcha.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            53 => 
            array (
                'id' => 54,
                'category_id' => 5,
                'name' => 'Teh Apple Hot',
                'slug' => 'Teh Apple Hot',
                'description' => 'Nikmati kesegaran Teh Apple Hot khas Sebatas Kopi.',
                'price' => '13000.00',
                'stock' => 100,
                'image' => 'products/Teh Apple.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            54 => 
            array (
                'id' => 55,
                'category_id' => 5,
                'name' => 'Teh Apple Cold',
                'slug' => 'Teh Apple Cold',
                'description' => 'Nikmati kesegaran Teh Apple Cold khas Sebatas Kopi.',
                'price' => '15000.00',
                'stock' => 100,
                'image' => 'products/Teh Apple.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            55 => 
            array (
                'id' => 56,
                'category_id' => 5,
                'name' => 'Teh Irish Hot',
                'slug' => 'Teh Irish Hot',
                'description' => 'Nikmati kesegaran Teh Irish Hot khas Sebatas Kopi.',
                'price' => '15000.00',
                'stock' => 100,
                'image' => 'products/Teh Irish.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            56 => 
            array (
                'id' => 57,
                'category_id' => 5,
                'name' => 'Teh Irish Cold',
                'slug' => 'Teh Irish Cold',
                'description' => 'Nikmati kesegaran Teh Irish Cold khas Sebatas Kopi.',
                'price' => '17000.00',
                'stock' => 100,
                'image' => 'products/Teh Irish.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            57 => 
            array (
                'id' => 58,
                'category_id' => 6,
                'name' => 'Milkshake Milo',
                'slug' => 'Milkshake Milo',
                'description' => 'Nikmati kesegaran Milkshake Milo khas Sebatas Kopi.',
                'price' => '15000.00',
                'stock' => 100,
                'image' => 'products/Milkshake Milo.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            58 => 
            array (
                'id' => 59,
                'category_id' => 6,
                'name' => 'Milkshake Strawberry',
                'slug' => 'Milkshake Strawberry',
                'description' => 'Nikmati kesegaran Milkshake Strawberry khas Sebatas Kopi.',
                'price' => '15000.00',
                'stock' => 100,
                'image' => 'products/Milkshake Strawberry.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            59 => 
            array (
                'id' => 60,
                'category_id' => 6,
                'name' => 'Milkshake Matcha',
                'slug' => 'Milkshake Matcha',
                'description' => 'Nikmati kesegaran Milkshake Matcha khas Sebatas Kopi.',
                'price' => '15000.00',
                'stock' => 100,
                'image' => 'products/Milkshake Matcha.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            60 => 
            array (
                'id' => 61,
                'category_id' => 6,
                'name' => 'Milkshake Vanilla',
                'slug' => 'Milkshake Vanilla',
                'description' => 'Nikmati kesegaran Milkshake Vanilla khas Sebatas Kopi.',
                'price' => '15000.00',
                'stock' => 100,
                'image' => 'products/Milkshake Vanilla.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            61 => 
            array (
                'id' => 62,
                'category_id' => 6,
                'name' => 'Milkshake Chocolate',
                'slug' => 'Milkshake Chocolate',
                'description' => 'Nikmati kesegaran Milkshake Chocolate khas Sebatas Kopi.',
                'price' => '15000.00',
                'stock' => 100,
                'image' => 'products/Milkshake Chocolate.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            62 => 
            array (
                'id' => 63,
                'category_id' => 6,
                'name' => 'Milkshake Caramel',
                'slug' => 'Milkshake Caramel',
                'description' => 'Nikmati kesegaran Milkshake Caramel khas Sebatas Kopi.',
                'price' => '15000.00',
                'stock' => 100,
                'image' => 'products/Milkshake Caramel.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            63 => 
            array (
                'id' => 64,
                'category_id' => 6,
                'name' => 'Milkshake Red Velvet',
                'slug' => 'Milkshake Red Velvet',
                'description' => 'Nikmati kesegaran Milkshake Red Velvet khas Sebatas Kopi.',
                'price' => '15000.00',
                'stock' => 100,
                'image' => 'products/Milkshake Red Velvet.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            64 => 
            array (
                'id' => 65,
                'category_id' => 6,
                'name' => 'Milkshake Taro',
                'slug' => 'Milkshake Taro',
                'description' => 'Nikmati kesegaran Milkshake Taro khas Sebatas Kopi.',
                'price' => '15000.00',
                'stock' => 100,
                'image' => 'products/Milkshake Taro.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            65 => 
            array (
                'id' => 66,
                'category_id' => 7,
                'name' => 'Mocktail Calamansi',
                'slug' => 'Mocktail Calamansi',
                'description' => 'Nikmati kesegaran Mocktail Calamansi khas Sebatas Kopi.',
                'price' => '20000.00',
                'stock' => 100,
                'image' => 'products/Mocktail Calamansi.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            66 => 
            array (
                'id' => 67,
                'category_id' => 7,
                'name' => 'Mocktail Iecy',
                'slug' => 'Mocktail Iecy',
                'description' => 'Nikmati kesegaran Mocktail Iecy khas Sebatas Kopi.',
                'price' => '20000.00',
                'stock' => 100,
                'image' => 'products/Mocktail Iecy.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            67 => 
            array (
                'id' => 68,
                'category_id' => 7,
                'name' => 'Mocktail Blueberry',
                'slug' => 'Mocktail Blueberry',
                'description' => 'Nikmati kesegaran Mocktail Blueberry khas Sebatas Kopi.',
                'price' => '20000.00',
                'stock' => 100,
                'image' => 'products/Mocktail Blueberry.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            68 => 
            array (
                'id' => 69,
                'category_id' => 7,
                'name' => 'Mocktail Mangga',
                'slug' => 'Mocktail Mangga',
                'description' => 'Nikmati kesegaran Mocktail Mangga khas Sebatas Kopi.',
                'price' => '20000.00',
                'stock' => 100,
                'image' => 'products/Mocktail Mangga.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            69 => 
            array (
                'id' => 70,
                'category_id' => 7,
                'name' => 'Mocktail Orange',
                'slug' => 'Mocktail Orange',
                'description' => 'Nikmati kesegaran Mocktail Orange khas Sebatas Kopi.',
                'price' => '20000.00',
                'stock' => 100,
                'image' => 'products/Mocktail Orange.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            70 => 
            array (
                'id' => 71,
                'category_id' => 8,
                'name' => 'Es Lemon Mint',
                'slug' => 'Es Lemon Mint',
                'description' => 'Nikmati kesegaran Es Lemon Mint khas Sebatas Kopi.',
                'price' => '23000.00',
                'stock' => 100,
                'image' => 'products/Es Lemon Mint.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            71 => 
            array (
                'id' => 72,
                'category_id' => 8,
                'name' => 'Es Chocolate Mint',
                'slug' => 'Es Chocolate Mint',
                'description' => 'Nikmati kesegaran Es Chocolate Mint khas Sebatas Kopi.',
                'price' => '23000.00',
                'stock' => 100,
                'image' => 'products/Es Chocolate Mint.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            72 => 
            array (
                'id' => 73,
                'category_id' => 8,
                'name' => 'Es White Chocolate Mint',
                'slug' => 'Es White Chocolate Mint',
                'description' => 'Nikmati kesegaran Es White Chocolate Mint khas Sebatas Kopi.',
                'price' => '23000.00',
                'stock' => 100,
                'image' => 'products/Es White Chocolate Mint.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            73 => 
            array (
                'id' => 74,
                'category_id' => 9,
                'name' => 'Kentang Goreng',
                'slug' => 'Kentang Goreng',
                'description' => 'Nikmati kesegaran Kentang Goreng khas Sebatas Kopi.',
                'price' => '18000.00',
                'stock' => 100,
                'image' => 'products/Kentang Goreng.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            74 => 
            array (
                'id' => 75,
                'category_id' => 9,
                'name' => 'Tempe Goreng',
                'slug' => 'Tempe Goreng',
                'description' => 'Nikmati kesegaran Tempe Goreng khas Sebatas Kopi.',
                'price' => '15000.00',
                'stock' => 100,
                'image' => 'products/Tempe Goreng.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            75 => 
            array (
                'id' => 76,
                'category_id' => 9,
                'name' => 'Nugget',
                'slug' => 'Nugget',
                'description' => 'Nikmati kesegaran Nugget khas Sebatas Kopi.',
                'price' => '18000.00',
                'stock' => 100,
                'image' => 'products/Nugget.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            76 => 
            array (
                'id' => 77,
                'category_id' => 9,
                'name' => 'Nasi Goreng',
                'slug' => 'Nasi Goreng',
                'description' => 'Nikmati kesegaran Nasi Goreng khas Sebatas Kopi.',
                'price' => '18000.00',
                'stock' => 100,
                'image' => 'products/Nasi Goreng.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            77 => 
            array (
                'id' => 78,
                'category_id' => 9,
                'name' => 'Nasi Telur',
                'slug' => 'Nasi Telur',
                'description' => 'Nikmati kesegaran Nasi Telur khas Sebatas Kopi.',
                'price' => '15000.00',
                'stock' => 100,
                'image' => 'products/Nasi Telur.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            78 => 
            array (
                'id' => 79,
                'category_id' => 9,
                'name' => 'Indomie Goreng',
                'slug' => 'Indomie Goreng',
                'description' => 'Nikmati kesegaran Indomie Goreng khas Sebatas Kopi.',
                'price' => '15000.00',
                'stock' => 100,
                'image' => 'products/Indomie Goreng.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
            79 => 
            array (
                'id' => 80,
                'category_id' => 9,
                'name' => 'Indomie Kuah',
                'slug' => 'Indomie Kuah',
                'description' => 'Nikmati kesegaran Indomie Kuah khas Sebatas Kopi.',
                'price' => '18000.00',
                'stock' => 100,
                'image' => 'products/Indomie Kuah.png',
                'is_available' => 1,
                'created_at' => '2026-08-15 15:16:46',
                'updated_at' => '2026-08-15 15:16:46',
            ),
        ));
        
        
    }
}