import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
            },
            colors: {
                "on-primary": "#ffffff",
                "on-primary-fixed-variant": "#5b403c",
                "tertiary-fixed-dim": "#e1c299",
                "surface-container": "#f4eceb",
                "primary": "#271310",
                "on-background": "#1e1b1a",
                "secondary-container": "#e1e1c9",
                "on-secondary-container": "#636451",
                "tertiary": "#241500",
                "primary-fixed": "#ffdad4",
                "on-secondary-fixed": "#1b1d0e",
                "inverse-on-surface": "#f7efee",
                "primary-container": "#3e2723",
                "on-surface-variant": "#504442",
                "on-secondary-fixed-variant": "#474836",
                "surface-container-low": "#faf2f0",
                "primary-fixed-dim": "#e3beb8",
                "outline": "#827472",
                "on-tertiary-fixed-variant": "#584324",
                "on-primary-container": "#ae8d87",
                "surface-tint": "#745853",
                "secondary-fixed-dim": "#c8c8b0",
                "on-primary-fixed": "#2b1613",
                "secondary-fixed": "#e4e4cc",
                "surface-container-high": "#eee6e5",
                "tertiary-container": "#3c290c",
                "on-tertiary-fixed": "#281801",
                "on-surface": "#1e1b1a",
                "surface-variant": "#e8e1df",
                "on-tertiary": "#ffffff",
                "surface-bright": "#fff8f6",
                "error": "#ba1a1a",
                "on-error": "#ffffff",
                "surface-dim": "#e0d8d7",
                "surface": "#fff8f6",
                "tertiary-fixed": "#feddb3",
                "on-error-container": "#93000a",
                "inverse-primary": "#e3beb8",
                "background": "#fff8f6",
                "error-container": "#ffdad6",
                "secondary": "#5e604d",
                "on-secondary": "#ffffff",
                "inverse-surface": "#33302f",
                "surface-container-lowest": "#ffffff",
                "on-tertiary-container": "#ab906a",
                "outline-variant": "#d3c3c0",
                "surface-container-highest": "#e8e1df",
            },
        },
    },

    plugins: [forms],
};
